version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.5.3.jar
          background: true
      - run:
          name: Build Test Jar
          command: |
            javac -cp "selenium-server-standalone-3.5.3.jar" TestButtonOutput.java
      - run:
          name: ls
          command: |
            ls
      - run:
          name: Run Test Jar
          command: |
            java -cp ".:selenium-server-standalone-3.5.3.jar" CircleCiTest.TestButtonOutput
      
